# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('club_description', mezzanine.core.fields.RichTextField(verbose_name='club description')),
                ('city', models.CharField(max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('activity', models.CharField(choices=[('daily', 'Every day'), ('weekly', 'Once a week'), ('fortnightly', 'Once per two weeks'), ('monthly', 'Once per month'), ('infrequently', 'Less than once a month'), ('not', 'This club has shut down')], default='weekly', max_length=12)),
                ('affiliated', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ('_order',),
            },
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='club', to='club.Interest'),
        ),
    ]
