# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('header_heading', models.CharField(help_text='The heading of the header.', max_length=200)),
                ('header_subheading', models.CharField(help_text='The heading of the sub-header.', max_length=200)),
                ('header_text', mezzanine.core.fields.RichTextField(verbose_name='Header text.')),
                ('header_link', models.CharField(help_text='Header link.', max_length=200)),
                ('featured_club', models.ForeignKey(blank=True, help_text='Items from a club will be shown on the home page', null=True, on_delete=django.db.models.deletion.CASCADE, to='club.Club')),
            ],
            options={
                'ordering': ('_order',),
            },
            bases=('pages.page', models.Model),
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('heading', models.CharField(help_text='Signup heading', max_length=200)),
            ],
            options={
                'ordering': ('_order',),
            },
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('quote', mezzanine.core.fields.RichTextField(verbose_name='Testimonial quote')),
            ],
        ),
    ]
