# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
        ('club', '0002_homepage_signup_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleColumn',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('club_elements', mezzanine.core.fields.RichTextField(verbose_name='Elements of a Club')),
                ('club_roles', mezzanine.core.fields.RichTextField(verbose_name='Club Roles')),
                ('club_types', mezzanine.core.fields.RichTextField(verbose_name='Types of Clubs')),
                ('regional_link_text', models.CharField(help_text='Link Text', max_length=200)),
                ('regional_link_url', models.CharField(help_text='Link URL', max_length=200)),
            ],
            options={
                'ordering': ('_order',),
            },
            bases=('pages.page', models.Model),
        ),
    ]
