# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_singlecolumn'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='testimonial',
            field=models.ForeignKey(blank=True, help_text='Choose a testimonial quote to display', null=True, on_delete=django.db.models.deletion.CASCADE, to='club.Testimonial'),
        ),
    ]
