# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_singlecolumn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlecolumn',
            name='club_elements',
        ),
        migrations.RemoveField(
            model_name='singlecolumn',
            name='club_roles',
        ),
        migrations.RemoveField(
            model_name='singlecolumn',
            name='club_types',
        ),
        migrations.RemoveField(
            model_name='singlecolumn',
            name='regional_link_text',
        ),
        migrations.RemoveField(
            model_name='singlecolumn',
            name='regional_link_url',
        ),
        migrations.AddField(
            model_name='singlecolumn',
            name='header_heading',
            field=models.CharField(default='', help_text='The heading of the header.', max_length=200),
        ),
        migrations.AddField(
            model_name='singlecolumn',
            name='header_text',
            field=mezzanine.core.fields.RichTextField(default='', verbose_name='Header text.'),
        ),
    ]
