# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-21 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import networkapi.opportunities.models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_opportunity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'ordering': ('order',), 'verbose_name_plural': 'opportunities'},
        ),
        migrations.AddField(
            model_name='opportunity',
            name='description',
            field=models.TextField(default='', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunity',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='image',
            field=models.FileField(default='', max_length=2048, upload_to=networkapi.opportunities.models.get_opportunities_image_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunity',
            name='link_label',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunity',
            name='link_url',
            field=models.URLField(default='', max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunity',
            name='name',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunity',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
