# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.Site'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('username', 'site')]),
        ),
    ]
