# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageWithCallout',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('name', models.CharField(max_length=500)),
                ('label', models.CharField(choices=[('read', 'Read and contribute'), ('write', 'Create and inspire')], default='read', max_length=12)),
                ('featured', models.BooleanField(default=False)),
                ('header', models.CharField(max_length=500)),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Main body content')),
            ],
            options={
                'ordering': ('_order',),
            },
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=4096)),
            ],
        ),
        migrations.AddField(
            model_name='pagewithcallout',
            name='signup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.Signup'),
        ),
    ]
