# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagewithcallout',
            name='signup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page', to='network.Signup'),
        ),
    ]
