# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 00:20
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20170324_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='name',
            new_name='header',
        ),
        migrations.AlterField(
            model_name='signup',
            name='description',
            field=mezzanine.core.fields.RichTextField(verbose_name='description'),
        ),
    ]
