# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20170324_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=500)),
                ('link', models.URLField(max_length=2048)),
            ],
        ),
    ]
