# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_footerlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerlink',
            name='icon',
            field=models.URLField(default='', max_length=2048),
            preserve_default=False,
        ),
    ]
