# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_footerlink_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='icon',
            field=models.CharField(max_length=2048),
        ),
    ]
