# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20170324_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footerlink',
            old_name='header',
            new_name='linktext',
        ),
        migrations.RemoveField(
            model_name='footerlink',
            name='icon',
        ),
        migrations.AddField(
            model_name='footerlink',
            name='iconclass',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='link',
            field=models.CharField(max_length=2048),
        ),
    ]
