# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20170327_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footerlink',
            old_name='linktext',
            new_name='header',
        ),
        migrations.RemoveField(
            model_name='footerlink',
            name='iconclass',
        ),
        migrations.AddField(
            model_name='footerlink',
            name='icon',
            field=models.CharField(default='', max_length=2048),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='link',
            field=models.URLField(max_length=2048),
        ),
    ]
