# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20170327_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footerlink',
            old_name='icon',
            new_name='iconclass',
        ),
    ]
