# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20170327_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footerlink',
            old_name='header',
            new_name='linktext',
        ),
    ]
