# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20170327_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='link',
            field=models.CharField(max_length=2048),
        ),
    ]
