# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_auto_20170327_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketNewsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
            ],
        ),
        migrations.AddField(
            model_name='signup',
            name='newsletter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='form', to='network.BasketNewsletter'),
        ),
    ]
