# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.PositiveSmallIntegerField()),
                ('name', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'discourse categories',
            },
        ),
    ]
