# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custompage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='fn',
            field=models.TextField(default='NO NAME GIVEN', verbose_name='Family name'),
        ),
        migrations.AddField(
            model_name='author',
            name='gn',
            field=models.TextField(default='NO NAME GIVEN', verbose_name='Given name'),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.TextField(null=True, verbose_name='ISBN'),
        ),
    ]
