# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custompage', '0004_club_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='content',
        ),
    ]
