# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 22:47
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('custompage', '0005_remove_club_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='content',
            field=mezzanine.core.fields.RichTextField(default='', verbose_name='Content'),
            preserve_default=False,
        ),
    ]
