# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custompage', '0006_club_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='content',
        ),
        migrations.AddField(
            model_name='club',
            name='club_description',
            field=models.TextField(blank=True, max_length=5000, verbose_name='club description'),
        ),
    ]
