# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 23:53
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('custompage', '0007_auto_20170313_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_description',
            field=mezzanine.core.fields.RichTextField(verbose_name='club description'),
        ),
    ]
