# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePage',
            new_name='GroupsGatheringsLandingPage',
        ),
        migrations.AlterModelOptions(
            name='groupsgatheringslandingpage',
            options={'verbose_name': 'Groups and Gatherings Landing Page'},
        ),
    ]
