# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170817_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('body_title', models.CharField(blank=True, default='', max_length=40)),
                ('body_text', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('info_title', models.CharField(blank=True, default='', max_length=40)),
                ('info_text', wagtail.wagtailcore.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'About Snippets',
            },
        ),
    ]
