# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('home', '0006_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsnippet',
            name='body_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='aboutsnippet',
            name='collaborators',
            field=wagtail.wagtailcore.fields.StreamField((('info', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock(help_text='General content field, appropriate for questions, titles etc (max 150 chars)', max_length=150)), ('text', wagtail.wagtailcore.blocks.RichTextBlock(blank=True, default='', help_text='WYSIWYG Editor for general purpose content, (max 1000 chars)', max_length=1000, required=False)), ('link', wagtail.wagtailcore.blocks.URLBlock(help_text='Optional field - accepts a URL (max 200 chars)', max_length=200, required=False)), ('link_title', wagtail.wagtailcore.blocks.CharBlock(help_text='Optional field - Title of the link, (max 100 chars)', max_length=100, required=False)), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False))))),), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutsnippet',
            name='collaborators_cta_link',
            field=models.URLField(blank=True, default='', verbose_name='CTA Link'),
        ),
        migrations.AddField(
            model_name='aboutsnippet',
            name='collaborators_cta_text',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='CTA Text'),
        ),
        migrations.AddField(
            model_name='aboutsnippet',
            name='collaborators_text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='aboutsnippet',
            name='collaborators_title',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='aboutsnippet',
            name='details',
            field=wagtail.wagtailcore.fields.StreamField((('section', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock(help_text='General content field, appropriate for questions, titles etc (max 150 chars)', max_length=150)), ('text', wagtail.wagtailcore.blocks.RichTextBlock(blank=True, default='', help_text='WYSIWYG Editor for general purpose content, (max 1000 chars)', max_length=1000, required=False)), ('link', wagtail.wagtailcore.blocks.URLBlock(help_text='Optional field - accepts a URL (max 200 chars)', max_length=200, required=False)), ('link_title', wagtail.wagtailcore.blocks.CharBlock(help_text='Optional field - Title of the link, (max 100 chars)', max_length=100, required=False))))),), blank=True, null=True, verbose_name='Blocks'),
        ),
        migrations.AddField(
            model_name='aboutsnippet',
            name='details_title',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='aboutsnippet',
            name='body_text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='aboutsnippet',
            name='body_title',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='aboutsnippet',
            name='bottom_cta_text',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='aboutsnippet',
            name='bottom_cta_title',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='aboutsnippet',
            name='info_text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='aboutsnippet',
            name='info_title',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='aboutsnippet',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
