# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170915_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsnippet',
            name='optional_text_block',
            field=wagtail.wagtailcore.fields.StreamField((('secondary_section', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock(help_text='General content field, appropriate for questions, titles etc (max 150 chars)', max_length=150)), ('text', wagtail.wagtailcore.blocks.RichTextBlock(blank=True, default='', help_text='WYSIWYG Editor for general purpose content, (max 1000 chars)', max_length=1000, required=False)), ('link', wagtail.wagtailcore.blocks.URLBlock(help_text='Optional field - accepts a URL (max 200 chars)', max_length=200, required=False)), ('link_title', wagtail.wagtailcore.blocks.CharBlock(help_text='Optional field - Title of the link, (max 100 chars)', max_length=100, required=False))))),), blank=True, null=True, verbose_name='Blocks'),
        ),
        migrations.AddField(
            model_name='aboutsnippet',
            name='optional_text_block_title',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Title'),
        ),
    ]
