# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0008_auto_20170915_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('Discourse', 'Discourse'), ('Github', 'Github'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Code of Conduct', 'Code of Conduct')], max_length=50)),
                ('url', models.URLField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
        ),
    ]
