# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('opensource_clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityImageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, default='', max_length=512)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='ClubPage',
            new_name='CategoryLandingPage',
        ),
        migrations.RenameModel(
            old_name='ClubsLandingPage',
            new_name='EntityDetailPage',
        ),
        migrations.RenameField(
            model_name='categorylandingpage',
            old_name='intro',
            new_name='description',
        ),
        migrations.AddField(
            model_name='entityimagegallery',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='opensource_clubs.EntityDetailPage'),
        ),
    ]
