# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discourse', '0001_initial'),
        ('opensource_clubs', '0002_auto_20170817_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorylandingpage',
            name='discourse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='discourse.DiscourseCategory'),
        ),
    ]
