# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_aboutsnippet'),
        ('wagtailcore', '0040_page_draft_title'),
        ('opensource_clubs', '0003_categorylandingpage_discourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('roles_captain', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('roles_coordinator', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('roles_member', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('about', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.AboutSnippet')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
