# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_testimonial'),
        ('opensource_clubs', '0005_auto_20170829_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorylandingpage',
            name='testimonial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.Testimonial'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.Testimonial'),
        ),
    ]
