# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opensource_clubs', '0008_activitiespage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='roles_captain',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='roles_coordinator',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='roles_member',
        ),
    ]
