# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('opensource_clubs', '0010_clubprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='bottom_cta1_link',
            field=models.URLField(blank=True, default='', verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='bottom_cta1_text',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='bottom_cta2_link',
            field=models.URLField(blank=True, default='', verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='bottom_cta2_text',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='bottom_cta_text',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='bottom_cta_title',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='heading_cta_link',
            field=models.URLField(blank=True, default='', verbose_name='CTA Link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='heading_cta_text',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='CTA Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='heading_text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, default='', verbose_name='Text'),
        ),
    ]
