# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('opensource_clubs', '0011_auto_20170911_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorylandingpage',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='categorylandingpage',
            name='testimonial',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='description',
        ),
        migrations.AddField(
            model_name='categorylandingpage',
            name='heading_cta_link',
            field=models.URLField(blank=True, default='', verbose_name='CTA Link'),
        ),
        migrations.AddField(
            model_name='categorylandingpage',
            name='heading_cta_text',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='CTA Text'),
        ),
        migrations.AddField(
            model_name='categorylandingpage',
            name='heading_text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, default='', verbose_name='Text'),
        ),
    ]
