# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('opensource_clubs', '0014_auto_20170913_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubprofile',
            name='avatar_url',
            field=models.URLField(blank=True, default='', max_length=400),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='github_link',
            field=models.URLField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='mozillian_username',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='title',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='entitydetailpage',
            name='club_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='entitydetailpage',
            name='contact_cta',
            field=models.URLField(blank=True, default='', verbose_name='Description social link'),
        ),
        migrations.AddField(
            model_name='entitydetailpage',
            name='description_link',
            field=models.URLField(blank=True, default='', verbose_name='Description link'),
        ),
        migrations.AddField(
            model_name='entitydetailpage',
            name='discourse_link',
            field=models.URLField(blank=True, default='', verbose_name='Discourse Link'),
        ),
        migrations.AddField(
            model_name='entitydetailpage',
            name='facebook_link',
            field=models.URLField(blank=True, default='', verbose_name='Facebook link'),
        ),
        migrations.AddField(
            model_name='entitydetailpage',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entitydetailpage',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='entitydetailpage',
            name='members',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='profiles', to='opensource_clubs.ClubProfile'),
        ),
    ]
