# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensource_clubs', '0016_auto_20170914_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitydetailpage',
            name='flag_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
