# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensource_clubs', '0017_entitydetailpage_flag_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitydetailpage',
            name='contact_cta',
            field=models.URLField(blank=True, verbose_name='Contact CTA link'),
        ),
    ]
