# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 11:26
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('opensource_clubs', '0018_auto_20170915_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcespage',
            name='bottom_content_block',
            field=wagtail.wagtailcore.fields.StreamField((('cta', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock(help_text='General content field, appropriate for questions, titles etc (max 150 chars)', max_length=150)), ('text', wagtail.wagtailcore.blocks.RichTextBlock(blank=True, default='', help_text='WYSIWYG Editor for general purpose content, (max 100 chars)', max_length=100, required=False)), ('link', wagtail.wagtailcore.blocks.URLBlock(help_text='Optional field - accepts a URL (max 200 chars)', max_length=200, required=False)), ('link_title', wagtail.wagtailcore.blocks.CharBlock(help_text='Optional field - Title of the link, (max 100 chars)', max_length=100, required=False)), ('cta_link', wagtail.wagtailcore.blocks.URLBlock(help_text='Optional field - accepts a URL (max 200 chars)', max_length=200, required=False)), ('cta_title', wagtail.wagtailcore.blocks.CharBlock(help_text='Optional field - Title of the link, (max 100 chars)', max_length=100, required=False))))),), blank=True, null=True),
        ),
    ]
