# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensource_clubs', '0022_auto_20171121_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
