# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('opensource_clubs', '0024_auto_20171127_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='opengraph_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Open Graph Image'),
        ),
    ]
