# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 22:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20170324_1546'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='ClubTopic',
        ),
    ]
